#:schema https://fnox.jdx.dev/schema.json

if_missing = "error"
env = "exec"

[providers]
keychain = { type = "keychain", service = "coda-api" }
age = { type = "age", recipients = ["age1sf4r4amev2svqr6llwg8hgtz9n7p5qdh7hh0mavcshzfrmgfduksnq3hql","age1605gsnxpe536sprwccyumq74veg0g80u55n8ggems0t8deau6qdsfnq3m3","age1hrluqkcgceu59n99fnxmjy3qe5fryut3myel5qzfyz6p6jrtxdns8n2xke"]}

[profiles]

[profiles.test]

[profiles.test.secrets]
CODA_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOEpkbWxWZktIeHlrN2tFbXZoVGt0V0k4eStWQlRZSnZqMzFxZjZJa3lrCjhWYjIrZ0duc3FaUnN1eVJ2cEZaZThSTFpwbjd4VUVQb0k4dW9GRGVJSlkKLT4gWDI1NTE5IGRTTFBzR0pEYVRKREhjTDEzYXpMTlIzeHJMbnh3MkRUQVJiTmRIdEJCM00KNjNEZUErUEtIVWR4OW1HTUZNOWlkcWlPaE5pUWpCajI4azA0aHVwSWtrVQotPiBYMjU1MTkgNkZrV01aYzlhbEE2NHdJd0tFT09hcGp1TERtajdvZ0ZaWTdkOFMxK1lnMAorNnVOZjY4aWlWWDc2dm9sdytvSFhpa1Y1aXg0Q3lkd2Y0NVJyZW4rSzE0Ci0+ICx9WzEtZ3JlYXNlIEAgeSB4e2VqICUxP2BvQiJjCmtQblBEejdLNzRJWnRHd042T2RyZmN1ZQotLS0gVnduM2c4TVMwSmw3bnM5bHlPdXV4dkRGdjVsZytGZngzNXNBVGdjeE11ZwpZhnFpeUo6OqzQLWdLugSw9mm6ou05Xvp3yEzv7jbfmJKP0P1pUCUDptfly/5jIS1/w2jByKOpXi2vhLdza8lWtRsFDQ==" }
CODA_DOC_ID= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWmw3QWRBVnFFSTV0djlWZjgyckNkTDFDVVFhZGFvdW90ODk3QmROMWhRCjg5MzNGem13TGpnb01pVTUzWVRMRiswOWh3MEdQVEZVa1dPRG9xWkZGalEKLT4gWDI1NTE5IHJsbXkrRkgvK1dwV0UyQ0p6WW5wdWtLSlg2aEZTakJhdW5sc1NFUkJ6aTAKczlCeTZYQWI2ZHJoc3hvclR0OGo0UnJSZm5JUWRRMFJPU05INzZrUE5tcwotPiBYMjU1MTkgTzNlajZEdGJHOTN4TEFDMDRyMlExREtGdzM2U1VwbG4wZFdxMVVEbUxnWQpzM01FV1RMZ3JZL2NWelBhVVhtU0c5cDlDVUYvblAyaHEyVGZCaC92WnFJCi0+IHpXdiQicmAtZ3JlYXNlIE9HWT5ANzcgIUxYWWogMnVfO19vdGcgPFVbcUQqZHUKc3NYU0pBaXNWV29rc0Z2dlA4OW5oN0t6dGJyelRIekdINTVseUJuRmVSSjIzcCtNOSszUlN4R2FTZ1hmd0pXRQpvUFVyNVNRRE4wd2VOMUtzUS9peE1ocld2aU9rUytvcDJub05ONHB1T3VjCi0tLSBGK3pNRjdGOXNMUGFKakNYL2xIbW1GamZIdzJPYStzUXREb295OXgyNWMwCjJJSHxWbtLbYOKdUoK7d5ZFuxH311LQeag+yzIWPywxMFNuQYCnPELtQQ==" }
